services:
  langfuse-worker:
    networks:
      - default

  langfuse-web:
    networks:
      - web_gateway
      - default

  clickhouse:
    networks:
      - default

  minio:
    networks:
      - web_gateway
      - default

  postgres:    
    networks:
      - default           

  redis:
    networks:
      - web_gateway
      - default

networks:
  web_gateway:
    external: true